### ISSUE TITLE
'Minetest' object has no attribute 'tool'

### ISSUE THREAD

**Issue by inf0maniac** [miney-py/miney#1]
Hello!
Thanks for this interesting tool. I am exploring it because it packages everything needed to do a complete coding experience for kids and any other interested person, no hassle on installing python and using PIP.
I am following the API documentation and tried to use the tool property, i.e, mt.tool but Python idle throws me the error 'Minetest' object has no attribute 'tool'. Do am I missing something? thanks in advance for this effort.
Regards

**Comment by Netzvamp** [comment]
Hi @inf0maniac , 
i'm currently in big changes not commited yet and due to corona i had no time for polish, but now when i see someone is interested, i'll take a look in it tomorrow and at the weekend. I was also thinking about education. Would be cool to get some input and help :)

**Comment by inf0maniac** [comment]
Many thanks @Netzvamp . I understand the current circumstances we are into.
I am from Colombia and on my mind long time ago had the idea of teaching basic coding concepts and skills to my students while I am also learning because I am just an amateur on everything related to coding. Because of the coronavirus there is no date here for returning to the classrooms. I could provide input on using this, but so far looks awesome and promissory.

**Comment by Netzvamp** [comment]
Hi @inf0maniac ,
sorry that i couldn't deliver in time, i'm still in the making. It's a bigger task than i thought, cause i've added many features in my current commit and skipped automatic testing some months ago ... that was a big mistake :P It takes longer, but it will be worth the wait. I've made big progress in node spawning and reading performance. When it's finished i'll deliver a stable foundation for more features ... i still belive this project is needed, so don't worry ;)

**Comment by inf0maniac** [comment]
@Netzvamp hi , don't mention it.  I understand the circumstances. I'm looking forward for it! of course it is a very much needed project since many teaching activities are halted due covid and in my personal case i see this tool as a way to teach my students concepts around programming and having them engaged, it also gives me time to solve local issues as some of them do not have pc in order to open minetest and the idle. thanks.

**Comment by Netzvamp** [comment]
hey, @inf0maniac
i've updated the package on pypi, so have a look :)

**Comment by inf0maniac** [comment]
Hello there ! I am going to check ASAP!

**Comment by inf0maniac** [comment]
Many thanks @Netzvamp i have already done a few tests and it is working awesome. I'ill be try this with my students for stem class
